name: Build Tablet URL lists & dumps

on:
  workflow_dispatch:
    inputs:
      locales:
        description: "Locales CSV (e.g. en,fr,es)"
        default: "en,fr,es,de,it,pt,ja,zh"
      arrival:
        description: "Arrival date YYYY-MM-DD"
        default: "2026-01-01"
      los:
        description: "Length of stay (nights)"
        default: "1"
      concurrency:
        description: "Parallel fetches for dumps"
        default: "10"
  push:
    paths:
      - reset_all.json
      - make_url_lists.js
      - build_tablet_dump.js
  schedule:
    - cron: "5 2 * * *"   # daily 02:05 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      # 1) Generate lists: urls/<locale>.txt
      - name: Generate URL lists (urls/*.txt)
        env:
          LOCALES: ${{ github.event.inputs.locales || 'en,fr,es,de,it,pt,ja,zh' }}
          ARRIVAL: ${{ github.event.inputs.arrival || '2026-01-01' }}
          LOS: ${{ github.event.inputs.los || '1' }}
        run: |
          node make_url_lists.js
          ls -l urls/*.txt

      # 2) Fetch Tablet responses and build dumps/<locale>.json
      - name: Build Tablet dumps (dumps/*.json)
        env:
          LOCALES: ${{ github.event.inputs.locales || 'en,fr,es,de,it,pt,ja,zh' }}
          CONCURRENCY: ${{ github.event.inputs.concurrency || '10' }}
        run: |
          node build_tablet_dump.js
          ls -l dumps/*.json

      # 3) Commit artifacts to the 'urls' branch
      - name: Commit artifacts to 'urls' branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: urls
          create_branch: true
          commit_message: "Build URL lists & dumps"
          file_pattern: |
            urls/*.txt
            dumps/*.json
          push_options: '--force-with-lease'
